- hosts: all

  tasks:
      - name: Add {{ user }} to sudoers
        lineinfile:
          dest: /etc/sudoers
          regexp: "{{ user }} ALL"
          line: "{{ user }} ALL=(ALL) NOPASSWD:ALL"
          state: present
